# Generated by Django 4.2.20 on 2025-04-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
    ]
